version: 2

defaults: &defaults
  docker:
    - image: circleci/node:7.10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /home
          # Must be relative path from root
          paths:
            - circleci/project/

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Unit-Test
          command: yarn test

      - run:
          name: Mutation-Test
          command: node_modules/.bin/stryker run

      - run:
          name: Report to Codacy
          command: node_modules/.bin/nyc report --reporter=lcov && cat ./docs/report/coverage/lcov.info | ./node_modules/.bin/codacy-coverage

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /^master$/